networks:
  radares-net:
    external: true

services:
  # ===============================================================
  # NOSSO MICROSSERVIÇO: Radar Cart
  # ===============================================================
  microservico-radar-cart:
    container_name: microservico-radares-cart
    # Em vez de 'image', usamos 'build' para construir a partir do nosso Dockerfile
    build:
      context: ../microservico-radares-cart # Caminho relativo para a pasta do projeto
    ports:
      - "8085:8085" # Expõe a porta do serviço para a sua máquina
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - rabbitmq.exchange.name=radares_exchange
      - rabbitmq.routing.key=radares.cart
      - FTP_HOST=${CART_FTP_HOST}
      - FTP_PORT=${CART_FTP_PORT}
      - FTP_USER=${CART_FTP_USER}
      - FTP_PASS=${CART_FTP_PASS}
    networks:
      - radares-net
    restart: unless-stopped
volumes:
  postgres-cart-data:
  pgadmin-data: # <-- Adicionar o novo volume aqui
  es-data:
